#!/usr/bin/env bash
set -oue pipefail

yay -S --noconfirm \
    fluxcd \
    chezmoi \
    fluxcd \
    helm \
    k9s \
    kubectl-bin \
    kubeseal \
    mise-bin \
    mkcert \
    neovim \
    nushell \
    p7zip \
    pnpm \
    podman-compose \
    rustup \
    tldr \
    unzip \
    visual-studio-code-bin \
    xclip \
    zip

rustup toolchain install stable-x86_64-unknown-linux-gnu

distrobox-export --app code